version: '3.3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    depends_on:
      zookeeper:
        condition: service_started
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "challenge.notification.update:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  legacy-payment-processor:
    image: legacy-payment-processor:latest
    container_name: legacy-payment-processor
    build:
      context: ./
      dockerfile: docker/Dockerfile









