version: '3'
services:
  legacy-payment-processor:
    image: legacy-payment-processor:latest
    container_name: legacy-payment-processor
    build:
      context: ../
      dockerfile: docker/Dockerfile
